name: client
#언제 job을 작동시킬건지
on:
  push:
    branches:
      reference
      #어떤 job을 할거냐
jobs:
  #빌드 할 때 밑에 작업
    build:
    #작업을 실행할 깃헙의 호스팅 러너
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout source code.
        #실행할 작업/깃헙에 릴리즈된 특정 버전 참조
          uses: actions/checkout@v2
        - name: Install dependencies
        #npm install을 실행
          run: npm install
          #npm install을 진행할 directory지정
          working-directory: ./my-agora-states-client
        - name: Build
          run: npm run build
          working-directory: ./my-agora-states-client
        - name: Sync Bucket
          env:
          # yml파일에 직접적으로 AWS ACCESS KEY ID와 ACCESS KEY를 집어넣으면 외부에 노출되므로 Github 리포지토리 - setting - secrets and variables 에서 repository secret 추가해 사용(ex 이름:AWS_ACCESS_KEY_ID, 내용: 값 입력)
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_EC2_METADATA_DISABLED: true
            # build 할 버킷을 입력
            # 작업할 스토리지
          run: |
            aws s3 sync \
              --region ap-northeast-2 \
              build s3://fe-76-doubl-e-s3 \
              --delete
          working-directory: ./my-agora-states-client
